### ISSUE TITLE
Unknown property 'crossorigin'

### ISSUE THREAD

**Issue by dnfd** [actpohabtNS/hackademy-week-5#2]
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  

Failed to compile.

./pages/_app.js
9:195  Error: Unknown property 'crossorigin' found, use 'crossOrigin' instead  react/no-unknown-property

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

**Comment by nksazonov** [comment]
Changed `crossorigin` to `crossOrigin`: https://github.com/actpohabtNS/hackademy-week-5/commit/41c53f3d086802f983e89db8114573147d225510.
